"""Export a session as a Markdown document."""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy.orm import Session as DBSession

from app.models import AssistantOutput, OcrSnapshot, Session, TranscriptChunk


def build_markdown_export(db: DBSession, session: Session) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    created = session.created_at.strftime("%Y-%m-%d %H:%M") if session.created_at else "—"

    lines: list[str] = [
        f"# Meeting Notes: {session.title}",
        f"",
        f"**Session ID:** {session.id}  ",
        f"**Started:** {created}  ",
        f"**Exported:** {now}",
        f"",
        f"---",
        f"",
    ]

    # Transcript
    chunks = (
        db.query(TranscriptChunk)
        .filter(TranscriptChunk.session_id == session.id)
        .order_by(TranscriptChunk.created_at.asc())
        .all()
    )
    if chunks:
        lines += ["## Transcript", ""]
        for c in chunks:
            ts = ""
            if c.start_time is not None:
                m, s = divmod(int(c.start_time), 60)
                ts = f"[{m:02d}:{s:02d}] "
            lines.append(f"{ts}{c.text}")
        lines.append("")

    # OCR snapshots
    snapshots = (
        db.query(OcrSnapshot)
        .filter(OcrSnapshot.session_id == session.id)
        .order_by(OcrSnapshot.captured_at.asc())
        .all()
    )
    if snapshots:
        lines += ["## Screen Captures (OCR Text)", ""]
        for snap in snapshots:
            cap_time = snap.captured_at.strftime("%H:%M:%S") if snap.captured_at else "—"
            lines += [
                f"### Captured at {cap_time}",
                "",
                f"```",
                snap.extracted_text,
                f"```",
                "",
            ]

    # Assistant outputs
    outputs = (
        db.query(AssistantOutput)
        .filter(AssistantOutput.session_id == session.id)
        .order_by(AssistantOutput.created_at.asc())
        .all()
    )
    if outputs:
        lines += ["## AI Assistant Outputs", ""]
        for i, out in enumerate(outputs, start=1):
            ts = out.created_at.strftime("%H:%M:%S") if out.created_at else "—"
            lines += [f"### Response {i} — {ts}", ""]

            if out.meeting_recap:
                lines += ["**Meeting Recap**", "", out.meeting_recap, ""]

            if out.suggested_response:
                lines += ["**Suggested Response**", "", f"> {out.suggested_response}", ""]

            if out.follow_up_question:
                lines += ["**Follow-up Question**", "", f"_{out.follow_up_question}_", ""]

            if out.action_items:
                lines += ["**Action Items**", ""]
                for item in out.action_items:
                    lines.append(f"- [ ] {item}")
                lines.append("")

    lines += ["---", "", "*Generated by LocalCopilot — ethical AI meeting assistant.*"]
    return "\n".join(lines)
